# Generated by Django 4.2.4 on 2023-08-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('tools', models.TextField()),
                ('repository', models.TextField()),
                ('host', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BigProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.project')),
                ('date1', models.DateField()),
                ('date2', models.DateField()),
            ],
            bases=('api.project',),
        ),
        migrations.CreateModel(
            name='SmallProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.project')),
                ('date', models.DateField()),
            ],
            bases=('api.project',),
        ),
    ]
